#!/bin/bash

chmod +rw ${COURSE_DIR}

# Define default values
data_url=""
env_url=""

# Parse command line arguments using getopt
while getopts ":d:e:" opt; do
  case $opt in
    d) data_url="$OPTARG"
    ;;
    e) env_url="$OPTARG"
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    ;;
  esac
done

# Check if both options are provided
if [[ -z $data_url || -z $env_url ]]; then
  echo "Usage: $0 -d <data_url> -e <env_url>"
  exit 1
fi

# Download the files using wget
if [ ! -d "Course_Env" ] 
    then
        echo "----------> downloading packages"
        mkdir -p ${COURSE_DIR}/Course_Env
        fix-permissions ${COURSE_DIR}/Course_Env
        wget -t 10 -O $env_url ${COURSE_DIR}/Course_Env.tar.gz
        echo "----------> extracting packages"
        tar -zxf ${COURSE_DIR}/Course_Env.tar.gz -C ${COURSE_DIR}/Course_Env
        rm -f ${COURSE_DIR}/Course_Env.tar.gz
    else
        ln -sf Course_Env ${COURSE_DIR}/Course_Env
    fi

    if [ ! -d "Data" ] 
    then 
        echo "----------> downloading data"
        mkdir -p ${COURSE_DIR}/Data
        fix-permissions ${COURSE_DIR}/Data
        wget -t 10 $data_url -O ${COURSE_DIR}/Data.tar.gz
        echo "----------> extracting data"
        tar -zxf ${COURSE_DIR}/Data.tar.gz -C ${COURSE_DIR}/Data
        rm -f ${COURSE_DIR}/Data.tar.gz ${COURSE_DIR}/Data.tar.gz 
    else
        ln -sf Data ${COURSE_DIR}/Data
    fi
