#!/bin/bash

while getopts c: option
do
    case "${option}"
    in
        c) COURSE=${OPTARG};;
        \?) ## Invalid option
            printf "Error: invalid option.\n\n"
            exit;;
    esac
done

PORT=8888

COURSE_DIR=/work/
mkdir -p ${COURSE_DIR}
fix-permissions ${COURSE_DIR}

ln -sf "${CONDA_DIR}"/envs/Course_Env ${COURSE_DIR}/Course_Env

printf  "\n==================  "
printf  "\n Selecting Course  \n"
printf  "==================  \n\n"

if [ "${COURSE}" == "Intro_to_NGS" ]
then
    echo "-----> Chosen course: Introduction to NGS data"

    if [ ! -d "Data" ]
    then
        echo "----------> downloading data"
        mkdir -p "${COURSE_DIR}"/Data
        fix-permissions "${COURSE_DIR}"/Data
        wget --show-progress -t 10 https://zenodo.org/record/7670370/files/Data.tar.gz?download=1 -O "${COURSE_DIR}"/Data.tar.gz
        echo "----------> extracting data"
        tar -zxf "${COURSE_DIR}"/Data.tar.gz -C "${COURSE_DIR}"/Data > /dev/null 2>&1
        rm -f "${COURSE_DIR}"/Data.tar.gz "${COURSE_DIR}"/Data.tar.gz
    else
        echo "----------> data already present"
    fi

    echo "----------> Installing course kernels on JupyterLab"
    "${COURSE_DIR}"/Course_Env/bin/python -m ipykernel install --user --name="ngs_python" --display-name "NGS (Python)"
    "${COURSE_DIR}"/Course_Env/bin/R -e "IRkernel::installspec(user=TRUE, name = 'ngs_r', displayname = 'NGS (R)')"

    
    git clone --depth 1 https://github.com/hds-sandbox/NGS_summer_course_Aarhus.git /home/"${NB_USER}"/course
    # kernel configurations with updated $PATH included
    cp /home/"${NB_USER}"/course/Environments/kernel_py.json ~/.local/share/jupyter/kernels/ngs_python/kernel.json && \
    cp /home/"${NB_USER}"/course/Environments/kernel_R.json ~/.local/share/jupyter/kernels/ngs_r/kernel.json

    
    mv /home/"${NB_USER}"/course/Scripts ${COURSE_DIR}/

    if [ ! -d "Notebooks" ]
    then
        echo "----------> copying course notebooks"
        mv /home/"${NB_USER}"/course/Notebooks "${COURSE_DIR}"/
    else
        echo "----------> notebooks already present"
    fi

    printf  "\n==================  "
    printf  "\n Start JupyterLab  \n"
    printf  "==================  \n\n"
    bash -c "jupyter lab --NotebookApp.token='' --ip=0.0.0.0 --port ${PORT}"

fi

if [ "${COURSE}" == "Intro_to_PopGen" ]
then
    echo "-----> Chosen course: Intro to population Genetics"

    if [ ! -d "Data" ]
    then
        echo "----------> downloading data"
        mkdir -p "${COURSE_DIR}"/Data
        fix-permissions "${COURSE_DIR}"/Data
        wget --show-progress -t 10 https://zenodo.org/record/7670839/files/Data.tar.gz?download=1 -O "${COURSE_DIR}"/Data.tar.gz
        echo "----------> extracting data"
        tar -zxf "${COURSE_DIR}"/Data.tar.gz -C "${COURSE_DIR}"/ > /dev/null 2>&1
        rm -f "${COURSE_DIR}"/Data.tar.gz
    else
        echo "----------> data already present"
    fi

    echo "----------> Installing course kernels on JupyterLab"
    "${COURSE_DIR}"/Course_Env/bin/python -m ipykernel install --user --name="args_dashboard" --display-name "args dashboard"
    "${COURSE_DIR}"/Course_Env/bin/R -e "IRkernel::installspec(user=TRUE, name = 'popgen_course', displayname = 'popgen course')"
    "${COURSE_DIR}"/Course_Env/bin/python -m bash_kernel.install

    git clone --branch ucloud --depth 1  https://github.com/hds-sandbox/PopulationGenomicsCourse.git /home/"${NB_USER}"/course

    if [ ! -d "Notebooks" ]
    then
        echo "----------> copying course notebooks"
        mv /home/"${NB_USER}"/course/Notebooks "${COURSE_DIR}"/
    else
        echo "----------> notebooks already present"
    fi

    # kernel configurations with updated $PATH included
    cp /home/"${NB_USER}"/course/uCloud/Configurations/kernelBash.json ~/.local/share/jupyter/kernels/bash/kernel.json

    printf  "\n==================  "
    printf  "\n Start JupyterLab  \n"
    printf  "==================  \n\n"

    bash -c "jupyter lab --NotebookApp.token='' --ip=0.0.0.0 --port ${PORT}"
fi

if [ "${COURSE}" == "Intro_to_GWAS" ]
then
    echo "-----> Chosen course: Intro to GWAS"

    git clone --depth 1  https://github.com/hds-sandbox/GWAS_course.git /home/"${NB_USER}"/course
    mv /home/"${NB_USER}"/Software "${COURSE_DIR}"/

    echo "----------> Installing course kernels on JupyterLab"
    "${COURSE_DIR}"/Course_Env/bin/python -m bash_kernel.install
    "${COURSE_DIR}"/Course_Env/bin/R -e "IRkernel::installspec(user=TRUE, name = 'rgwas', displayname = 'GWAS (R)')"
    # kernel configurations with updated $PATH included
    cp /home/"${NB_USER}"/course/uCloud/kernelBash.json ~/.local/share/jupyter/kernels/bash/kernel.json
    
    if [ ! -d "Data" ]
    then
        echo "----------> copying data"
        mv /home/"${NB_USER}"/course/Data "${COURSE_DIR}"/
        fix-permissions "${COURSE_DIR}"/Data
    else
        echo "----------> data already present"
    fi

    if [ ! -d "Notebooks" ]
    then
        echo "----------> copying notebooks"
        mv /home/"${NB_USER}"/course/Notebooks "${COURSE_DIR}"/
    else
        echo "----------> notebooks already present"
    fi

    printf  "\n==================  "
    printf  "\n Start JupyterLab  \n"
    printf  "==================  \n\n"

    bash -c "jupyter lab --NotebookApp.token='' --log-level=50 --ip=0.0.0.0 --port ${PORT}"
fi

if [ "${COURSE}" == "IGV" ]
then
    echo "-----> Chosen tool: Interactive Genomic Browser"
    cd /usr/igv-webapp || exit
    npx http-server --port "${PORT}" -a 0.0.0.0 dist
fi
