#!/bin/bash

PORT_USER=8787
COURSE_DIR=/tmp/course

## Options for the Transcriptomics Sandbox app
while getopts c:f:p: option; do
    case "${option}" in
    c) COURSE=${OPTARG} ;;
    p) PORT_USER=${OPTARG} ;; # not needed on ucloud!!!
    \?)                          ## Invalid option
        printf "Error: invalid option.\n\n"
        exit
        ;;
    esac
done



printf "\n======================  "
printf "\n== Selecting Module == \n"
printf "======================  \n\n"

if [ "${COURSE}" == "Intro_to_NGS" ]
then
    echo "-----> Chosen course: Introduction to NGS data"

    if [ ! -d "Data" ]
    then
        echo "----------> downloading data"
        mkdir -p Data
        wget --show-progress -t 10 https://zenodo.org/record/7670370/files/Data.tar.gz?download=1 -O /tmp/Data.tar.gz
        echo "----------> extracting data"
        tar -zxf /tmp/Data.tar.gz -C Data > /dev/null 2>&1
        rm -f /tmp/Data.tar.gz 
    else
        echo "----------> data already present"
    fi

    echo "----------> Installing course kernels on JupyterLab"
    /opt/miniconda/envs/Course_Env/bin/python -m ipykernel install --user --name="ngs_python" --display-name "NGS (Python)"
    /opt/miniconda/envs/Course_Env/bin/R -e "IRkernel::installspec(user=TRUE, name = 'ngs_r', displayname = 'NGS (R)')"

    
    git clone --depth 1 https://github.com/hds-sandbox/NGS_summer_course_Aarhus.git $COURSE_DIR
    # kernel configurations with updated $PATH included
    cp /home/ucloud/course/Environments/kernel_py.json ~/.local/share/jupyter/kernels/ngs_python/kernel.json && \
    cp /home/ucloud/course/Environments/kernel_R.json ~/.local/share/jupyter/kernels/ngs_r/kernel.json

    
    mv $COURSE_DIR/Scripts 

    if [ ! -d "Notebooks" ]
    then
        echo "----------> copying course notebooks"
        mv "${COURSE_DIR}"/Notebooks .
    else
        echo "----------> notebooks already present"
    fi

    #bashrc file for conda
    echo 'eval "$(/opt/miniconda/bin/conda shell.bash hook)"'>>/home/ucloud/.bashrc   
    echo 'conda activate /opt/miniconda/envs/Course_Env'>>/home/ucloud/.bashrc

    printf  "\n==================  "
    printf  "\n Start JupyterLab  \n"
    printf  "==================  \n\n"

    SHELL=/bin/bash jupyter-lab --port=$PORT_USER --ip=0.0.0.0 --NotebookApp.token='' --no-browser

fi

if [ "${COURSE}" == "Intro_to_PopGen" ]
then
    echo "-----> Chosen course: Intro to population Genetics"

    if [ ! -d "Data" ]
    then
        echo "----------> downloading data"
        wget --show-progress -t 10 https://zenodo.org/record/7670839/files/Data.tar.gz?download=1 -O /tmp/Data.tar.gz
        echo "----------> extracting data"
        tar -zxf /tmp/Data.tar.gz -C . > /dev/null 2>&1
        rm -f /tmp/Data.tar.gz
    else
        echo "----------> data already present"
    fi

    echo "----------> Installing course kernels on JupyterLab"
    /opt/miniconda/envs/Course_Env/bin/python -m ipykernel install --user --name="args_dashboard" --display-name "args dashboard"
    /opt/miniconda/envs/Course_Env/bin/R -e "IRkernel::installspec(user=TRUE, name = 'popgen_course', displayname = 'popgen course')"
    /opt/miniconda/envs/Course_Env/bin/python -m bash_kernel.install

    git clone --branch ucloud --depth 1  https://github.com/hds-sandbox/PopulationGenomicsCourse.git $COURSE_DIR

    if [ ! -d "Notebooks" ]
    then
        echo "----------> copying course notebooks"
        mv $COURSE_DIR/Notebooks .
    else
        echo "----------> notebooks already present"
    fi

    # kernel configurations with updated $PATH included
    cp $COURSE_DIR/uCloud/Configurations/kernelBash.json ~/.local/share/jupyter/kernels/bash/kernel.json

    #bashrc file for conda
    echo 'eval "$(/opt/miniconda/bin/conda shell.bash hook)"'>>/home/ucloud/.bashrc   
    echo 'conda activate /opt/miniconda/envs/Course_Env'>>/home/ucloud/.bashrc

    printf  "\n==================  "
    printf  "\n Start JupyterLab  \n"
    printf  "==================  \n\n"

    SHELL=/bin/bash jupyter-lab --port=$PORT_USER --ip=0.0.0.0 --NotebookApp.token='' --no-browser

fi

if [ "${COURSE}" == "Intro_to_GWAS" ]
then
    echo "-----> Chosen course: Intro to GWAS"

    git clone --depth 1  https://github.com/hds-sandbox/GWAS_course.git $COURSE_DIR
    mv $COURSE_DIR/Software .

    echo "----------> Installing course kernels on JupyterLab"
    /opt/miniconda/envs/Course_Env/bin/python -m bash_kernel.install
    /opt/miniconda/envs/Course_Env/Course_Env/bin/R -e "IRkernel::installspec(user=TRUE, name = 'rgwas', displayname = 'GWAS (R)')"
    
    if [ ! -d "Data" ]
    then
        echo "----------> copying data"
        mv COURSE_DIR/Data .
    else
        echo "----------> data already present"
    fi

    if [ ! -d "Notebooks" ]
    then
        echo "----------> copying notebooks"
        mv $COURSE_DIR/Notebooks .
    else
        echo "----------> notebooks already present"
    fi

    # kernel configurations with updated $PATH included
    cp /home/ucloud/course/uCloud/kernelBash.json ~/.local/share/jupyter/kernels/bash/kernel.json
    
    #bashrc file for conda
    echo 'eval "$(/opt/miniconda/bin/conda shell.bash hook)"'>>/home/ucloud/.bashrc   
    echo 'conda activate /opt/miniconda/envs/Course_Env'>>/home/ucloud/.bashrc

    printf  "\n==================  "
    printf  "\n Start JupyterLab  \n"
    printf  "==================  \n\n"

    SHELL=/bin/bash jupyter-lab --port=$PORT_USER --ip=0.0.0.0 --NotebookApp.token='' --no-browser

fi

if [ "${COURSE}" == "IGV" ]
then
    echo "-----> Chosen tool: Interactive Genomic Browser"
    export IGV_DATA_PATH="/work"
    cd /usr/igv-webapp || exit
    npx http-server --port "${PORT_USER}" -a 0.0.0.0 dist
fi
