#!/bin/bash

PORT_USER=8787
COURSE_DIR=/tmp/course
PIXI_ENV=/opt/pixi/envs/Course_Env/.pixi/envs/default
export PIXI_ENV
JUPYTER_KERNELS=$PIXI_ENV/share/jupyter/kernels
CURR_DIR=/work

##########################
##### Script options
##########################

while getopts :c:p: option; do
    case "${option}" in
    c) COURSE=${OPTARG} ;;    # Course to start
    p) PORT_USER=${OPTARG} ;; # needed only for general use out of ucloud
    \?)                       # Invalid option
        printf "Error: invalid option.\n\n"
        exit
        ;;
    esac
done

#########################
##### General setup
#########################

# Setup resource usage in topbar for jupyterlab
sed -i 's/"default": false/"default": true/g' "$PIXI_ENV/share/jupyter/labextensions/@jupyter-server/resource-usage/schemas/@jupyter-server/resource-usage/topbar-item.json"

#Initialize Pixi
cd $CURR_DIR || exit

#Course kernels setup for executables
echo "-----> Mapping course kernels on JupyterLab"
# shellcheck disable=SC2016,SC2044
for KERNEL in $(find $JUPYTER_KERNELS -name kernel.json)
do
    echo "----------> Mapping $KERNEL"
    jq '. + {"env": {"PATH":"$PIXI_ENV/bin/:$PIXI_ENV/libexec:$PATH"}}' "$KERNEL" > tmp.$$.json && mv tmp.$$.json "$KERNEL"
done

printf "\n======================  "
printf "\n== Selecting Module == \n"
printf "======================  \n\n"

cd $CURR_DIR || exit

#########################
##### intro to NGS course
#########################
if [ "${COURSE}" == "Intro_to_NGS" ]
then

    echo "-----> Chosen course: Introduction to NGS data"

    #Checking for course material
    if [ ! -d "Data" ]
    then
        echo "----------> downloading data"
        mkdir -p Data
        wget --show-progress -t 10 https://zenodo.org/record/7670370/files/Data.tar.gz?download=1 -O /tmp/Data.tar.gz
        echo "----------> extracting data"
        tar -zxf /tmp/Data.tar.gz -C Data > /dev/null 2>&1
        rm -f /tmp/Data.tar.gz
    else
        echo "----------> data already present"
    fi

    if [[ ! -d "Notebooks" || ! -d "Scripts" ]]
    then
    	git clone --no-checkout --filter=blob:none --depth 1 https://github.com/hds-sandbox/Intro-NGS-AU_course.git "$COURSE_DIR"
        cd "$COURSE_DIR" || exit
        git sparse-checkout init --cone
        git sparse-checkout set Notebooks Scripts
        git checkout
        cd $CURR_DIR || exit
    fi

    if [ ! -d "Scripts" ]
    then
        echo "----------> copying course notebooks"
        mv $COURSE_DIR/Scripts .
    else
        echo "----------> scripts already present"
    fi

    if [ ! -d "Notebooks" ]
    then
        echo "----------> copying course notebooks"
        mv $COURSE_DIR/Notebooks .
    else
        echo "----------> notebooks already present"
    fi

    printf  "\n==================  "
    printf  "\n Start JupyterLab  \n"
    printf  "==================  \n\n"

    cd "$PIXI_ENV" || exit
    SHELL="$PIXI_ENV/bin/bash" pixi run jupyter-lab --allow-root \
                                                    --port="$PORT_USER" \
                                                    --ip=0.0.0.0  \
                                                    --ServerApp.token='' \
                                                    --ResourceUseDisplay.track_cpu_percent=True \
                                                    --ResourceUseDisplay.track_disk_usage=True \
                                                    --ResourceUseDisplay.enable_prometheus_metrics=False \
                                                    --ContentsManager.allow_hidden=True \
                                                    --ServerApp.root_dir="$CURR_DIR"

fi

##########################
##### Popgen Aarhus Course
##########################

if [ "${COURSE}" == "Intro_to_PopGen" ]
then

    echo "-----> Chosen course: Intro to population Genetics"
    #Checking for course material

    if [ ! -d "Data" ]
    then
        echo "----------> downloading data"
        wget --show-progress -t 10 https://zenodo.org/record/7670839/files/Data.tar.gz?download=1 -O /tmp/Data.tar.gz
        echo "----------> extracting data"
        tar -zxf /tmp/Data.tar.gz -C . > /dev/null 2>&1
        rm -f /tmp/Data.tar.gz
    else
        echo "----------> data already present"
    fi

    if [ ! -d "Notebooks" ]
    then
        git clone --branch ucloud --no-checkout --filter=blob:none --depth 1  https://github.com/hds-sandbox/PopulationGenomicsAU_course.git "$COURSE_DIR"
        cd "$COURSE_DIR" || exit
        git sparse-checkout init --cone
        git sparse-checkout set Notebooks
        git checkout
        cd $CURR_DIR || exit
        echo "----------> copying course notebooks"
        mv $COURSE_DIR/Notebooks .
    else
        echo "----------> notebooks already present"
    fi

    printf  "\n==================  "
    printf  "\n Start JupyterLab  \n"
    printf  "==================  \n\n"

    cd "$PIXI_ENV" || exit
    SHELL="$PIXI_ENV/bin/bash" pixi run jupyter-lab --allow-root \
                                                    --port="$PORT_USER" \
                                                    --ip=0.0.0.0  \
                                                    --ServerApp.token='' \
                                                    --ResourceUseDisplay.track_cpu_percent=True \
                                                    --ResourceUseDisplay.track_disk_usage=True \
                                                    --ResourceUseDisplay.enable_prometheus_metrics=False \
                                                    --ContentsManager.allow_hidden=True \
                                                    --ServerApp.root_dir="$CURR_DIR"

fi

##########################
##### Intro to GWAS course
##########################

if [ "${COURSE}" == "Intro_to_GWAS" ]
then

    echo "-----> Chosen course: Intro to GWAS"

    #Checking for course material

    if [ ! -d "Data" ]
    then
        echo "----------> copying data"
        git clone --no-checkout --filter=blob:none  --depth 1  https://github.com/hds-sandbox/GWAS_course.git "$COURSE_DIR"
        cd "$COURSE_DIR" || exit
        git sparse-checkout init --cone
        git sparse-checkout set Data
        git checkout
        cd $CURR_DIR || exit
        mv $COURSE_DIR/Data .
        rm -rf $COURSE_DIR
    else
        echo "----------> data already present"
    fi

    if [ ! -d "Notebooks" ]
    then
        echo "----------> copying notebooks"
        git clone --no-checkout --filter=blob:none  --depth 1  https://github.com/hds-sandbox/GWAS_course.git "$COURSE_DIR"
        cd "$COURSE_DIR" || exit
        git sparse-checkout init --cone
        git sparse-checkout set Notebooks
        git checkout
        cd $CURR_DIR || exit
        mv $COURSE_DIR/Notebooks .
        rm -rf $COURSE_DIR
    else
        echo "----------> notebooks already present"
    fi

    printf  "\n==================  "
    printf  "\n Start JupyterLab  \n"
    printf  "==================  \n\n"

    cd "$PIXI_ENV" || exit
    SHELL="$PIXI_ENV/bin/bash" pixi run jupyter-lab --allow-root \
                                                    --port="$PORT_USER" \
                                                    --ip=0.0.0.0  \
                                                    --ServerApp.token='' \
                                                    --ResourceUseDisplay.track_cpu_percent=True \
                                                    --ResourceUseDisplay.track_disk_usage=True \
                                                    --ResourceUseDisplay.enable_prometheus_metrics=False \
                                                    --ContentsManager.allow_hidden=True \
                                                    --ServerApp.root_dir="$CURR_DIR"

fi
