#!/work/.pixi/envs/default/bin/bash

PORT_USER=8787
COURSE_DIR=/tmp/course
JUPYTER_KERNELS=/home/ucloud/.local/share/jupyter/kernels
PIXI_ENV=/work/.pixi/envs/default

##########################
##### Script options
##########################

while getopts c:f:p: option; do
    case "${option}" in
    c) COURSE=${OPTARG} ;;    # Course to start
    p) PORT_USER=${OPTARG} ;; # needed only for general use out of ucloud
    \?)                       # Invalid option
        printf "Error: invalid option.\n\n"
        exit
        ;;
    esac
done

#########################
#####General setup
#########################

# Setup resource usage in topbar for jupyterlab
sed -i 's/"default": false/"default": true/g' $PIXI_ENV/share/jupyter/labextensions/@jupyter-server/resource-usage/schemas/@jupyter-server/resource-usage/topbar-item.json

#Initialize Pixi
export PATH=$PATH:/home/ucloud/.pixi/bin && eval "$(pixi completion --shell bash)"



printf "\n======================  "
printf "\n== Selecting Module == \n"
printf "======================  \n\n"

#########################
##### intro to NGS course
#########################

if [ "${COURSE}" == "Intro_to_NGS" ]
then
    echo "-----> Chosen course: Introduction to NGS data"

    if [ ! -d "Data" ]
    then
        echo "----------> downloading data"
        mkdir -p Data
        wget --show-progress -t 10 https://zenodo.org/record/7670370/files/Data.tar.gz?download=1 -O /tmp/Data.tar.gz
        echo "----------> extracting data"
        tar -zxf /tmp/Data.tar.gz -C Data > /dev/null 2>&1
        rm -f /tmp/Data.tar.gz 
    else
        echo "----------> data already present"
    fi

    echo "----------> Installing course kernels on JupyterLab"
    pixi run python -m ipykernel install --user --name="ngs_python" --display-name "NGS (Python)"
    pixi run R -e "IRkernel::installspec(user=TRUE, name = \"ngs_r\", displayname = \"NGS (R)\")"

    
    for KERNEL in `find ~/.local/share/jupyter/kernels/ -name kernel.json`
    do 
        echo "----------> Editing $KERNEL"
        jq '. + {"env": {"PATH":"/opt/pixi/envs/Course_Env/.pixi/envs/default/bin/:/opt/pixi/envs/Course_Env/.pixi/envs/default/bin/libexec:$PATH"}}' $KERNEL > tmp.$$.json && mv tmp.$$.json $KERNEL
    done

    git clone --depth 1 https://github.com/hds-sandbox/NGS_summer_course_Aarhus.git $COURSE_DIR
    
    mv $COURSE_DIR/Scripts .

    if [ ! -d "Notebooks" ]
    then
        echo "----------> copying course notebooks"
        mv $COURSE_DIR/Notebooks .
    else
        echo "----------> notebooks already present"
    fi

    printf  "\n==================  "
    printf  "\n Start JupyterLab  \n"
    printf  "==================  \n\n"

    SHELL=/work/.pixi/envs/default/bin/bash pixi run jupyter-lab \
                                                        --port=$PORT_USER \
                                                        --ip=0.0.0.0  \
                                                        --NotebookApp.token='' \
                                                        --no-browser \
                                                        --ResourceUseDisplay.track_cpu_percent=True \
                                                        --ResourceUseDisplay.track_disk_usage=True \
                                                        --ResourceUseDisplay.enable_prometheus_metrics=False \
                                                        --ContentsManager.allow_hidden=True

fi

##########################
##### Popgen Aarhus Course
##########################

if [ "${COURSE}" == "Intro_to_PopGen" ]
then
    echo "-----> Chosen course: Intro to population Genetics"

    if [ ! -d "Data" ]
    then
        echo "----------> downloading data"
        wget --show-progress -t 10 https://zenodo.org/record/7670839/files/Data.tar.gz?download=1 -O /tmp/Data.tar.gz
        echo "----------> extracting data"
        tar -zxf /tmp/Data.tar.gz -C . > /dev/null 2>&1
        rm -f /tmp/Data.tar.gz
    else
        echo "----------> data already present"
    fi

    echo "----------> Installing course kernels on JupyterLab"
    .pixi/envs/default/bin/python -m ipykernel install --user --name="args_dashboard" --display-name "args dashboard"
    .pixi/envs/default/bin/R -e "IRkernel::installspec(user=TRUE, name = 'popgen_course', displayname = 'popgen course')"
    .pixi/envs/default/bin/python -m bash_kernel.install

    for KERNEL in `find ~/.local/share/jupyter/kernels/ -name kernel.json`
    do 
        echo "----------> Editing $KERNEL"
        jq '. + {"env": {"PATH":"/opt/pixi/envs/Course_Env/.pixi/envs/default/bin/:/opt/pixi/envs/Course_Env/.pixi/envs/default/bin/libexec:$PATH"}}' $KERNEL > tmp.$$.json && mv tmp.$$.json $KERNEL
    done    

    git clone --branch ucloud --depth 1  https://github.com/hds-sandbox/PopulationGenomicsCourse.git $COURSE_DIR

    if [ ! -d "Notebooks" ]
    then
        echo "----------> copying course notebooks"
        mv $COURSE_DIR/Notebooks .
    else
        echo "----------> notebooks already present"
    fi

    printf  "\n==================  "
    printf  "\n Start JupyterLab  \n"
    printf  "==================  \n\n"

    SHELL=/work/.pixi/envs/default/bin/bash pixi run jupyter-lab \
                                                        --port=$PORT_USER \
                                                        --ip=0.0.0.0  \
                                                        --NotebookApp.token='' \
                                                        --no-browser \
                                                        --ResourceUseDisplay.track_cpu_percent=True \
                                                        --ResourceUseDisplay.track_disk_usage=True \
                                                        --ResourceUseDisplay.enable_prometheus_metrics=False \
                                                        --ContentsManager.allow_hidden=True
fi

##########################
##### Intro to GWAS course
##########################

if [ "${COURSE}" == "Intro_to_GWAS" ]
then
    echo "-----> Chosen course: Intro to GWAS"

    git clone --depth 1  https://github.com/hds-sandbox/GWAS_course.git $COURSE_DIR
    mv $COURSE_DIR/Software .

    echo "----------> Installing course kernels on JupyterLab"
    .pixi/envs/default/bin/python -m bash_kernel.install
    .pixi/envs/default/bin/R -e "IRkernel::installspec(user=TRUE, name = 'rgwas', displayname = 'GWAS (R)')"

    for KERNEL in `find ~/.local/share/jupyter/kernels/ -name kernel.json`
    do 
        echo "----------> Editing $KERNEL"
        jq '. + {"env": {"PATH":"/opt/pixi/envs/Course_Env/.pixi/envs/default/bin/:/opt/pixi/envs/Course_Env/.pixi/envs/default/bin/libexec:$PATH"}}' $KERNEL > tmp.$$.json && mv tmp.$$.json $KERNEL
    done  
    
    if [ ! -d "Data" ]
    then
        echo "----------> copying data"
        mv $COURSE_DIR/Data .
    else
        echo "----------> data already present"
    fi

    if [ ! -d "Notebooks" ]
    then
        echo "----------> copying notebooks"
        mv $COURSE_DIR/Notebooks .
    else
        echo "----------> notebooks already present"
    fi

    printf  "\n==================  "
    printf  "\n Start JupyterLab  \n"
    printf  "==================  \n\n"

     SHELL=/work/.pixi/envs/default/bin/bash pixi run jupyter-lab \
                                                        --port=$PORT_USER \
                                                        --ip=0.0.0.0  \
                                                        --NotebookApp.token='' \
                                                        --no-browser \
                                                        --ResourceUseDisplay.track_cpu_percent=True \
                                                        --ResourceUseDisplay.track_disk_usage=True \
                                                        --ResourceUseDisplay.enable_prometheus_metrics=False \
                                                        --ContentsManager.allow_hidden=True

fi